### ISSUE TITLE
Bosses using npc.Transform() instantly disappear

### ISSUE THREAD

**Issue by direwolf420** [Naharie/NoBossDistanceDespawn#1]
[Issue description by a forum user](https://forums.terraria.org/index.php?threads/the-thorium-mod.40788/page-555#post-2451705)

These bosses use `npc.Transform()` within their AI to change phases.

**Comment by Naharie** [comment]
From my forum post: "This should now be resolved with v0.8 (the current mod browser release). So if you could give it another whirl, that would be great. It works on my machine, but that's no guarantee for you, so any feedback on that point is appreciated."

Technical note: the issue was that tModLoader doesn't copy instances of global npc classes over during the transform call which led to a null reference exception. Which now that I look closer could have happened in other edge cases, so it's great catch either way.

**Comment by Naharie** [comment]
As it has been a couple of days and I have not heard back regarding any issues with the new update, I will close this issue for now. If something else arises a new issue can be made or this one can be reopened.
